# Generated by Django 4.1.7 on 2023-05-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MontantMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('total', models.FloatField()),
                ('total_of_month', models.FloatField()),
            ],
            options={
                'db_table': 'recouvrement_montantmensuel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification_chef_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'recouvrement_notification_chef_service',
                'managed': False,
            },
        ),
    ]
