# Generated by Django 3.2 on 2023-07-01 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montantmensuel',
            name='total',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='montantmensuel',
            name='total_of_month',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
