# Generated by Django 4.1.7 on 2023-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_Batiment', models.CharField(max_length=120)),
                ('nb_logts', models.PositiveIntegerField()),
                ('nb_etage', models.PositiveIntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'db_table': 'data_batiment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_Cite', models.CharField(max_length=120)),
                ('nb_logts', models.PositiveIntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'db_table': 'data_cite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'data_consultation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cnt', models.DateTimeField(null=True)),
                ('date_strt_loyer', models.DateTimeField(null=True)),
                ('loyer', models.FloatField()),
                ('charge', models.CharField(max_length=120)),
                ('mnt_tva', models.FloatField()),
                ('total_of_month', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'data_contrat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.FloatField(default='m2')),
                ('prix_logement', models.FloatField()),
                ('type_logement', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_logement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_id', models.PositiveIntegerField(unique=True)),
                ('nom_oc', models.CharField(max_length=120)),
                ('prenom_oc', models.CharField(max_length=120)),
                ('date_naiss', models.DateTimeField(null=True)),
                ('lieu_naiss', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_occupant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_unit', models.CharField(max_length=120)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'db_table': 'data_unite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_wilaya', models.CharField(max_length=120)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'db_table': 'data_wilaya',
                'managed': False,
            },
        ),
    ]
