# Generated by Django 4.1.7 on 2023-03-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_contentieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.occupant')),
            ],
        ),
    ]
