# Generated by Django 4.1.7 on 2023-03-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_consultation_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='contrat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET, to='data.contrat'),
            preserve_default=False,
        ),
    ]
