# Generated by Django 4.1.7 on 2023-03-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_consultation_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='contrat',
        ),
    ]
