# Generated by Django 4.1.7 on 2023-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('nom_oc', models.CharField(max_length=255)),
                ('prenom_oc', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'chat_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service_contentieux_dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('dossier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminer', 'Terminer')], max_length=20)),
            ],
            options={
                'db_table': 'chat_service_contentieux_dossier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service_contentieux_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fix_par_opgi', models.FloatField()),
            ],
            options={
                'db_table': 'chat_service_contentieux_settings',
                'managed': False,
            },
        ),
    ]
