# Generated by Django 4.1.7 on 2023-05-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_dette', models.FloatField(default=0)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.consultation')),
            ],
            options={
                'db_table': 'data_dette',
            },
        ),
    ]
